version: '3.8'

services:
  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Logging__LogLevel__Default=Information
    volumes:
      - ./src/Services/OrderService/OrderService.Api:/app/src

  stockservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Logging__LogLevel__Default=Information
    volumes:
      - ./src/Services/StockService/StockService.Api:/app/src

  notificationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Logging__LogLevel__Default=Information
    volumes:
      - ./src/Services/NotificationService/NotificationService.Api:/app/src